sudo: required
dist: trusty
language: node_js

script: >
    npm run build &&
    npm run test-build

notifications:
  email:
    recipients:
      - eyale@wix.com

after_success:
  - npm run coveralls
